# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebavalidacionletras():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pruebavalidacionletras(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1184, 672)
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("a")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("9")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("2")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("9")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").send_keys("4")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("0")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("8")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("-1")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("8")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("9")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("-9")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("-8")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("9")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("8")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("8")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("0")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("4")
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("a")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.ID, "masa").click()
    self.driver.find_element(By.ID, "masa").send_keys("a")
    self.driver.find_element(By.ID, "aceleracion").click()
    self.driver.find_element(By.ID, "aceleracion").send_keys("9")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    elements = self.driver.find_elements(By.ID, "error")
    assert len(elements) > 0
  
